#### ChatReplay Configuration

# How many of the most recent chat messages to store in total
bufferSize: 500

# How many messages to show players at once
# Vanilla Minecraft Client has a history limit of around 100
viewSize: 70

### Formatting

## Header and footer message of replay output
# Available variables: {{msgCount}}
replayHeader: "&7&lReplaying last {{msgCount}} messages"
replayFooter: "&7&lReplayed last {{msgCount}} messages"

## Formatting for single messages replayed
# Available variables: {{player}}, {{message}}, {{timestamp}}
replayMsgFormat: "&7[{{player}}]: {{message}}"
replayMsgHover: "{{timestamp}}"