name: ChatReplay
version: 1.3.1
description: Replay chat history
author: Tallcraft
website: https://tallcraft.com

main: com.tallcraft.chatreplay.ChatReplay
database: false
commands:
 chatreplay:
    usage: /chatreplay <play|more|reload>
    permission-message: You do not have permission to use this command.
permissions:
 chatreplay.*:
   description: All permissions for ChatReplay
   default: op
   children:
     chatreplay.all: true
 chatreplay.all:
   description: All permissions for ChatReplay
   default: false
   children:
     chatreplay.reload: true
     chatreplay.view: true
 chatreplay.reload:
   description: Reload plugin config
   default: false
 chatreplay.view:
   description: View replayed chat
   default: true