name: ChatReplay
version: 1.4.0
description: Replay chat history
author: Tallcraft
website: https://tallcraft.com

main: com.tallcraft.chatreplay.ChatReplay
database: false
commands:
 chatreplay:
    usage: /chatreplay <play|more|reload>
    permission-message: You do not have permission to use this command.
permissions:
 chatreplay.*:
   description: All permissions for ChatReplay
   default: op
   children:
     chatreplay.all: true
 chatreplay.all:
   description: All permissions for ChatReplay
   default: false
   children:
     chatreplay.reload: true
     chatreplay.view: true
 chatreplay.reload:
   description: Reload plugin config
   default: false
 chatreplay.view:
   description: View replayed chat including history on login and via command
   default: true
   children:
     chatreplay.play: true
     chatreplay.more: true
     chatreplay.playlogin: true
 chatreplay.play:
   description: View most recent chat
   default: false
 chatreplay.more:
   description: View older chat messages
   default: false
 chatreplay.playlogin:
   description: Replay chat on login
   default: false